apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: jose
  name: jose
spec:
  selector:
    matchLabels:
      run: jose
  template:
    metadata:
      labels:
        run: jose
    spec:
      containers:
      - name: jose
        args:
        - run
        image: aialferov/jose
        imagePullPolicy: Always
        stdin: true
        tty: true
        ports:
        - containerPort: 8080
