-define(JobsApiUsage,
    "POST /api/v1/jobs[?tasks=<flatten|scriptize>] # default: scriptize~n"
    "{~n"
    "  \"tasks\":[~n"
    "    {~n"
    "      \"name\":\"<Task Name>\",~n"
    "      \"command\":\"<Shell Command>\"~n"
    "      \"requires\":[ # optional~n"
    "        \"<Task Name>\"~n"
    "        ...~n"
    "      ]~n"
    "    },~n"
    "    ...~n"
    "   ]~n"
    "}~n"
).

-define(JobsExample,
    "$ cat example.json~n"
    "{~n"
    "  \"tasks\":[~n"
    "    {~n"
    "      \"name\":\"task-1\",~n"
    "      \"command\":\"cat /tmp/file1\",~n"
    "      \"requires\":[~n"
    "        \"task-2\"~n"
    "      ]~n"
    "    },~n"
    "    {~n"
    "      \"name\":\"task-2\",~n"
    "      \"command\":\"echo 'Hello World!' > /tmp/file1\",~n"
    "    }~n"
    "  ]~n"
    "}~n"
    "~n"
    "$ curl -sd @example.json localhost:8080/api/v1/jobs?tasks=flatten | jq~n"
    "[~n"
    "  {~n"
    "    \"command\": \"echo 'Hello World!' > /tmp/file1\",~n"
    "    \"name\": \"task-2\"~n"
    "  },~n"
    "  {~n"
    "    \"command\": \"cat /tmp/file1\",~n"
    "    \"name\": \"task-1\"~n"
    "  }~n"
    "]~n"
    "~n"
    "$ curl -sd @example.json localhost:8080/api/v1/jobs?tasks=scriptize~n"
    "#!/bin/bash~n"
    "~n"
    "echo 'Hello World!' > /tmp/file1~n"
    "cat /tmp/file1~n"
).
